version: '3'
services:
    db:
        image: mysql:latest
        container_name: test_sql
        ports:
            -  '3306:3306'
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: employees
        cap_add:
            - SYS_NICE
        volumes:
            - ./data/employees.sql:/docker-entrypoint-initdb.d/employees.sql
            - db_data:/var/lib/mysql
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
volumes:
    db_data:
        driver: local
        #external: true
