version: '3'
services:
    #py_app:
    #build: .
    #   container_name: py_app
    #   ports:
    #       - '5000:5000'
    #   volumes: 
    #       - ./app:/app
    db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: sql1
        ports:
            -  '1433:1433'
        restart: always
        environment:
            ACCEPT_EULA: Y
            SA_PASSWORD: Il0vc34k3!
        volumes:
            #- ./data/employees.sql:/docker-entrypoint-initdb.d/employees.sql
            - db_data:/var/lib/mysql
volumes:
    db_data:
        driver: local
        #external: true
